services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2233
      POSTGRES_DB: expense_tracker
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:2233@db:5432/expense_tracker
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET_KEY: c666e4c89a820d737b6d1e8f6c30c456c2cc2ae0f30c93ebc0a30253dce7d9b9
    depends_on:
      - db
      - redis

volumes:
  pgdata:
  redisdata:
